version: '3'

shopt: [globstar]

# Глобальные переменные проекта
vars:
  GO_VERSION: '1.25'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'
  BUF_VERSION: '1.53.0'
  PROTOC_GEN_GO_VERSION: 'v1.36.6'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.5.1'
  PROTOC_GEN_VALIDATE_VERSION: 'v1.2.1'
  PROTOC_GEN_GRPC_GATEWAY_VERSION: 'v2.26.3'
  PROTOC_GEN_OPENAPIV2_VERSION: 'v2.26.3'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint.exe'
  GCI: '{{.BIN_DIR}}/gci.exe'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt.exe'
  BUF: '{{.BIN_DIR}}/buf'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  PROTOC_GEN_VALIDATE: '{{.BIN_DIR}}/protoc-gen-validate'
  PROTOC_GEN_GRPC_GATEWAY: '{{.BIN_DIR}}/protoc-gen-grpc-gateway'
  PROTOC_GEN_OPENAPIV2: '{{.BIN_DIR}}/protoc-gen-openapiv2'

tasks:
  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo 'Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo 'Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    cmds:
      - |
        mkdir -p "{{.BIN_DIR}}"
        if [ ! -f "{{.GOLANGCI_LINT}}" ]; then
          echo "Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN="{{.BIN_DIR}}" go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        fi
    status:
      - test -f "{{.GOLANGCI_LINT}}"


  install-buf:
    desc: "Устанавливает Buf в каталог bin"
    cmds:
      - |
        mkdir -p {{.BIN_DIR}}
        [ -f {{.BUF}} ] || {
          echo 'Устанавливаем buf {{.BUF_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@v{{.BUF_VERSION}}
        }
    status:
      - test -x {{.BUF}}


  proto:install-plugins:
    desc: "Устанавливает protoc плагины в каталог bin"
    cmds:
      - |
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo 'Installing protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
        }

        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo 'Installing protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
        }

        [ -f {{.PROTOC_GEN_GRPC_GATEWAY}} ] || {
          echo '📦 Installing protoc-gen-grpc-gateway...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@{{.PROTOC_GEN_GRPC_GATEWAY_VERSION}}
        }

        [ -f {{.PROTOC_GEN_VALIDATE}} ] || {
          echo '📦 Installing protoc-gen-validate...'
          GOBIN={{.BIN_DIR}} go install github.com/envoyproxy/protoc-gen-validate@{{.PROTOC_GEN_VALIDATE_VERSION}}
        }
        [ -f {{.PROTOC_GEN_OPENAPIV2}} ] || {
          echo 'Installing protoc-gen-openapiv2...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@{{.PROTOC_GEN_OPENAPIV2_VERSION}}
        }        

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    deps: [ install-formatters ]
    cmds:
      - |
        echo "Форматируем через gofumpt ..."
        for file in **/*.go; do
          case "$file" in
            */mocks/*) continue ;;
          esac
          "{{.GOFUMPT}}" -extra -w "$file"
        done

      - |
        echo "Сортируем импорты через gci ..."
        for file in **/*.go; do
          case "$file" in
            */mocks/*) continue ;;
          esac
          "{{.GCI}}" write -s standard -s default -s "prefix(github.com/SigmarWater/messenger/)" "$file"
        done

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [ install-golangci-lint ]
    cmds:
      - '"{{.GOLANGCI_LINT}}" run ./... --config=.golangci.yml'

  proto:update-deps:
    deps: [ install-buf ]
    desc: Обновляет зависимости protobuf из удаленных репозиториев (googleapis и т.д.)
    dir: proto
    cmds:
      - |
        echo "Обновляем зависимости buf..."
        ../bin/buf.exe dep update

  proto:lint:
    deps: [proto:install-plugins, proto:update-deps]
    desc: Проверка .proto-файлов на соответствие стилю
    dir: proto
    cmds:
      - |
        echo "Проверяем .proto файлы..."
        ../bin/buf.exe lint


  proto:gen-code:
    deps: [proto:install-plugins, proto:update-deps]
    desc: Генерация Go-кода из .proto
    # dir - дириктория, откуда выполняются команды, в нашем случае proto
    # (поэтому мы и пишем ../bin/buf.exe)
    # dir должна указывать на директорию, где находится buf.yaml и buf.gen.yaml.
    # «Перед выполнением команды перейди в директорию proto.»
    dir: proto
    cmds:
      - |
        echo "Генерируем Go код из .proto..."
        ../bin/buf.exe generate --template buf.gen.yaml

  proto:gen:
    deps: [proto:gen-code]
    desc: Генерация документации
    dir: proto
    cmds:
      - |
        echo "Генерируем Go документацию..."
        ../bin/buf.exe generate --template buf.gen.openapi.yaml

  start:server:
    cmds:
      - |
        echo "Запускаем сервер..."
        go run ./cmd/server/main.go

  start:client:
    cmds:
      - |
        echo "Запускаем клиент..."
        go run ./cmd/client/main.go