syntax = "proto3";

package jwt_service.v1;

option go_package = "crm/shared/pkg";
import "google/protobuf/timestamp.proto";

// Запрос на логин
message LoginRequest{
  string username = 1;
  string password = 2;
}

// Ответ на логин
message LoginResponse{
  string access_token = 1;
  string refresh_token = 2;
  google.protobuf.Timestamp access_token_expires_at = 3;
  google.protobuf.Timestamp refresh_token_expires_at = 4;
}

// Запрос на получение access токена
message GetAccessTokenRequest{
  string refresh_token = 1;
}

// Ответ с новым access токеном
message GetAccessTokenResponse{
  string access_token = 1;
  google.protobuf.Timestamp access_token_expires_at = 2;
}

// Запрос на получение refresh токена
message GetRefreshTokenRequest {
  string refresh_token = 1;
}

// Ответ с новым refresh токеном
message GetRefreshTokenResponse {
  string refresh_token = 1;
  google.protobuf.Timestamp refresh_token_expires_at = 2;
}


