version: v2

plugins:
  - local: ../bin/protoc-gen-openapiv2
    out: ../docs/openapi
    opt:
      - allow_merge=true
      - merge_file_name=crm
      - json_names_for_fields=true

# path внутри inputs — это фильтр:
# какие именно .proto файлы из указанной директории использовать как вход генерации.
inputs:
  - directory: .
    paths:
      - crm_service/v1/crm_service.proto