syntax = "proto3";

package crm_service.v1;

option go_package = "crm/pkg/api/crm_service";

import "google/protobuf/timestamp.proto";
import "validate/validate.proto";

// Клиент CRM-системы.
message Client {
  // Уникальный идентификатор клиента
  string uuid = 1 [
    (validate.rules).string.uuid = true
  ];
  // Имя клиента
  string name = 2 [
    (validate.rules).string = {
      min_len: 2
      max_len: 100
    }
  ];
  // Номер телефона клиента
  string phone = 3 [
    (validate.rules).string.pattern = "^\\+[1-9][0-9]{9,14}$"
  ];
  // Email клиента
  string email = 4 [
    (validate.rules).string = {
      email: true
      max_len: 255
    }
  ];

  google.protobuf.Timestamp created_at = 5;

  google.protobuf.Timestamp updated_at = 6;
}


// Запрос на создание клиента
message CreateClientRequest {
  // Имя клиента
  string name = 1 [
    (validate.rules).string = {
      min_len: 2
      max_len: 100
    }
  ];
  // Номер телефона клиента
  string phone = 2 [
    (validate.rules).string.pattern = "^\\+[1-9][0-9]{9,14}$"
  ];
  // Email клиента
  string email = 3 [
    (validate.rules).string = {
      email: true
      max_len: 255
    }
  ];
}
// Ответ на создание клиента
message CreateClientResponse {
  // Созданный клиент
  Client client = 1 [
    (validate.rules).message.required = true
  ];
}

// Запрос на получение клиента
message GetClientRequest {
  // UUID клиента
  string uuid = 1 [
    (validate.rules).string.uuid = true
  ];
}

// Ответ с информацией о клиенте
message GetClientResponse {
  // Найденный клиент
  Client client = 1 [
    (validate.rules).message.required = true
  ];
}

// Запрос на частичное обновление клиента.
message UpdateClientRequest{
  // UUID клиента
  string uuid = 1 [
    (validate.rules).string.uuid = true
  ];
  // Имя клиента
  optional string name = 2 [
    (validate.rules).string = {
      min_len: 2
      max_len: 100
    }
  ];
  // Номер телефона клиента
  optional string phone = 3 [
    (validate.rules).string.pattern = "^\\+[1-9][0-9]{9,14}$"
  ];
  // Email клиента
  optional string email = 4 [
    (validate.rules).string = {
      email: true
      max_len: 255
    }
  ];
}

// Ответ на обновление клиента.
message UpdateClientResponse{
  // Обновленный клиент
  Client client = 1 [
    (validate.rules).message.required = true
  ];
}

// Запрос на удаление клиента.
message DeleteClientRequest{
  // Уникальный идентификатор клиента
  string uuid = 1 [
    (validate.rules).string.uuid = true
  ];
}

// Запрос на получение списка клиентов.
message ListClientsRequest {
  int32 page_size = 1;
  string page_token = 2;

  string search = 3;

  string sort_by = 4;
  string sort_order = 5;
}

// Ответ со списком клиентов.
message ListClientsResponse {
  repeated Client clients = 1;

  string next_page_token = 2;
}