syntax="proto3";

package crm.proto.api.crm_service;

option go_package = "crm/pkg/api/crm_service";

import "google/protobuf/wrappers.proto";

enum Role{
  ROLE_UNSPECIFIED = 0;
  ROLE_USER = 1;
  ROLE_ADMIN = 2;
};


message Client {
  string uuid = 1;
  string name = 2;
  string phone = 3;
  string email = 4;
}

message CreateClientRequest {
  string name = 1;
  string phone = 2;
  string email = 3;
}

message CreateClientResponse {
  Client client = 1;
}

message GetClientRequest {
  string uuid = 1;
}

message GetClientResponse {
  Client client = 1;
}

